# Generated by Django 5.0.4 on 2024-06-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="address_1",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="address_2",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="job",
            name="city",
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="away_team",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="job",
            name="home_team",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="job",
            name="league",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(max_length=128),
        ),
    ]
