# Generated by Django 5.0.4 on 2024-06-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobboard", "0002_job_address_1_job_address_2_job_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
