# Generated by Django 5.0.4 on 2024-06-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobboard", "0003_alter_club_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="zip_code",
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
