# Generated by Django 5.0.4 on 2024-06-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobboard", "0004_job_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="state",
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
    ]
