# Generated by Django 5.0.4 on 2024-07-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobboard", "0005_job_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="title",
            field=models.TextField(blank=True),
        ),
    ]
