# Generated by Django 5.0.4 on 2024-07-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobboard", "0006_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="pay",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
